dist: trusty
language: node_js
sudo: false
node_js:
- 6
- 7
- 8
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - AWS_ACCESS_KEY_ID=fake
  - AWS_SECRET_ACCESS_KEY=fake
  - DYNAMO_DB_ENDPOINT=http://127.0.0.1:8000
before_script:
  - wget https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_2017-04-22_beta.tar.gz -O /tmp/dynamodb_local_latest.tar.gz
  - tar -xzf /tmp/dynamodb_local_latest.tar.gz -C /tmp
  - java -Djava.library.path=/tmp/DynamoDBLocal_lib -jar /tmp/DynamoDBLocal.jar -inMemory &
  - "timeout=0; until curl localhost:8000 > /dev/null 2>&1 || [ $timeout -eq 60 ]; do echo 'waiting for dynamo: '$timeout; sleep 2; timeout=$((timeout+1)); done"
cache:
  directories:
  - node_modules
