
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master

version: 2
jobs:
  build-node-8:
    docker:
      - image: node:8.9.3
      - image: dwmkerr/dynamodb
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-dynaflow-{{ checksum "package.json" }}
      - run:
          name: Test
          environment:
            COVERALLS_SERVICE_NAME: travis-pro
          command: |
            npm run coveralls
      - save_cache:
          key: npm-dynaflow-{{ checksum "package.json" }}
          paths:
            - "./node_modules"
