
workflows:
  version: 2
  build:
    jobs:
      - build-node-8:
          filters:
            branches:
              ignore:
                - master

version: 2
jobs:
  build-node-8:
    docker:
      - image: node:8.9.3
      - image: dwmkerr/dynamodb
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-dynaflow-{{ checksum "package.json" }}
      - run: npm install
      - run: npm test && nyc report --reporter=lcov && cat ./coverage/lcov.info
      - save_cache:
          key: npm-dynaflow-{{ checksum "package.json" }}
          paths:
            - "./node_modules"
